---

- name: install MySQL
  apt:
    name: {{ item }}
    state: present
    with_items:
      - mysql-server
      #- mysql

#- name: copy my.cnf
  #copy:
    #src: /home/gabyf/ansible-devops/roles/mysql/files/my.cnf
    #dest: /etc/my.cnf
    #owner: root
    #mode: 0600

- name: start MySQL
  notify:
    - start mysql
    #- restart mysql
