---

- name: install MySQL
  apt:
    name: {{ item }}
    state: present
    with_items:
      - mysql-server
      #- mysql
    notify:
      - start mysql

- name: configure MySQL
  copy:
    src: {{ mysqld_src_path }}
    dest: {{ mysqld_dest_path }}
    owner: root
    group: root
    mode: 0644

- name: set bind-address MySQL
  command: 'sed -i "s/.*bind-address.*/bind-address = {{ binded_address  }}/" /etc/mysql/mysql.conf.d/mysqld.cnf'

- name: create wordpress db and restart MySQL
  notify:
    - create wpdb
    - restart mysql
    
